---
- name: gather Cloud/OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_bios_version }}-{{ ansible_distribution }}.yml'
    - '{{ cloud_platform }}-{{ ansible_distribution }}.yml'

- name: install certbot-auto
  become: true
  copy:
    src: 'certbot-auto'
    dest: '/usr/local/bin/'
    mode: '0755'
    owner: '{{ USER.user }}'
    group: '{{ USER.user }}'

- name: create ssl certificate
  shell: 'certbot-auto certonly --standalone --email dev@harmony.one -d {{ domain }} -q --agree-tos'

- name: change owner of certificates
  become: true
  file:
    dest: '/etc/letsencrypt/{{ item }}'
    owner: '{{ USER.user }}'
    group: '{{ USER.user }}'
    recurse: yes
  with_items:
    - 'live'
    - 'archive'

- name: setup cron task renew ssl certificate
  cron:
    name: renew ssl certificate
    job: '/usr/local/bin/certbot-auto renew --pre-hook "sudo iptables -t nat -D PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080" --post-hook "sudo iptables -t nat -I PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080" --quiet'
    minute: '0'
    hour: '3'
    day: '*'
    month: '*'
    weekday: '*'


# vim: set expandtab:ts=2