---
- hosts: '{{ inventory }}'
  remote_user: '{{ user }}'
  gather_facts: yes
  tasks:
  - name: stop harmony system service
    command: systemctl stop harmony
    ignore_errors: yes
  - name: stop harmony
    command: sudo pkill harmony
    ignore_errors: yes
  - name: clean up
    ignore_errors: yes
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - harmony_db_0
      - harmony_db_1
      - harmony_db_2
      - harmony_db_3
      - harmony
      - latest
      - staging
      - hmy
      - node.sh
      - harmony.service
      - node.err
      - node.log
      - harmony-update.out
