---
- hosts: '{{ inventory }}'
  remote_user: '{{ ansible_user }}'
  gather_facts: yes
  vars:
    - node_type_var: "{{ node_type | default('Validator') }}"
  roles:
    - { role: node, network: mainnet }
