---
- hosts: '{{ inventory }}'
  gather_facts: yes

  tasks:
  - name: install required packages on node
    package:
      name: '{{ item }}'
      state: present
    become: true
    with_items:
      - jq
