---
- hosts: '{{ inventory }}'
  remote_user: '{{ user }}'
  gather_facts: yes
  become: true
  tasks:
  - name: gather OS specific variables
    include_vars: "{{ item }}"
    with_first_found:
      - '{{ ansible_bios_version }}-{{ ansible_distribution }}.yml'
      - '{{ cloud_platform }}-{{ ansible_distribution }}.yml'
  - name: kernel tuning
    lineinfile:
      dest: /etc/sysctl.conf
      regexp: "^{{ item.name }}="
      line: "{{ item.name }}={{ item.value }}"
    with_items:
      - { name: 'fs.file-max', value: '2097152' }
      - { name: 'vm.swappiness', value: '10' }
      - { name: 'vm.dirty_ratio', value: '60' }
      - { name: 'vm.dirty_background_ratio', value: '2' }
      - { name: 'kernel.sched_migration_cost_ns', value: '5000000' }
  - name: general network security options
    lineinfile:
      dest: /etc/sysctl.conf
      regexp: "^{{ item.name }}="
      line: "{{ item.name }}={{ item.value }}"
    with_items:
      - { name: 'net.ipv4.tcp_synack_retries', value: '2' }
      - { name: 'net.ipv4.ip_local_port_range', value: '2000 65535' }
      - { name: 'net.ipv4.tcp_rfc1337', value: '1' }
      - { name: 'net.ipv4.tcp_syncookies', value: '1' }
      - { name: 'net.ipv4.tcp_fin_timeout', value: '15' }
      - { name: 'net.ipv4.tcp_keepalive_time', value: '300' }
      - { name: 'net.ipv4.tcp_keepalive_probes', value: '5' }
      - { name: 'net.ipv4.tcp_keepalive_intvl', value: '15' }
  - name: tuning network performance
    lineinfile:
      dest: /etc/sysctl.conf
      regexp: "^{{ item.name }}="
      line: "{{ item.name }}={{ item.value }}"
    with_items:
      - { name: 'net.core.rmem_default', value: '31457280' }
      - { name: 'net.core.rmem_max', value: '33554432' }
      - { name: 'net.core.wmem_default', value: '31457280' }
      - { name: 'net.core.wmem_max', value: '33554432' }
      - { name: 'net.core.somaxconn', value: '8096' }
      - { name: 'net.core.netdev_max_backlog', value: '65536' }
      - { name: 'net.core.optmem_max', value: '25165824' }
      - { name: 'net.ipv4.tcp_max_syn_backlog', value: '8192' }
      - { name: 'net.ipv4.tcp_mem', value: '786432 1048576 26777216' }
      - { name: 'net.ipv4.udp_mem', value: '65536 131072 262144' }
      - { name: 'net.ipv4.tcp_rmem', value: '8192 87380 33554432' }
      - { name: 'net.ipv4.udp_rmem_min', value: '16384' }
      - { name: 'net.ipv4.tcp_wmem', value: '8192 65536 33554432' }
      - { name: 'net.ipv4.udp_wmem_min', value: '16384' }
      - { name: 'net.ipv4.tcp_max_tw_buckets', value: '1440000' }
      - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
      - { name: 'net.ipv4.tcp_fastopen', value: '3' }
      - { name: 'net.ipv4.tcp_window_scaling', value: '1' }
  - name: "active the configuration in sysctl.conf"
    shell: "sysctl -p"
  - name: "add env to limits.conf"
    shell: "grep -qxF \"{{ item }}\" /etc/security/limits.conf || echo \"{{ item }}\" >> /etc/security/limits.conf"
    with_items:
      - "* soft     nproc          65535"
      - "* hard     nproc          65535"
      - "* soft     nofile         65535"
      - "* hard     nofile         65535"
      - "root soft     nproc          65535"
      - "root hard     nproc          65535"
      - "root soft     nofile         65535"
      - "root hard     nofile         65535"
  - name: "add env to common-session"
    shell: "grep -qxF \"session required pam_limits.so\" /etc/pam.d/common-session || echo \"session required pam_limits.so\" >> /etc/pam.d/common-session"