---
- hosts: '{{ inventory }}'
  remote_user: '{{ user }}'
  gather_facts: yes
  become: true
  tasks:
  - name: kernel tuning
    command: "{{ item }}"
    with_items:
      - "sysctl -w fs.file-max=2097152"
      - "sysctl -w vm.swappiness=10"
      - "sysctl -w vm.dirty_ratio=60"
      - "sysctl -w vm.dirty_background_ratio=2"
      - "sysctl -w kernel.sched_migration_cost_ns=5000000"
  - name: general network security options
    command: "{{ item }}"
    with_items:
      - "sysctl -w net.ipv4.tcp_synack_retries=2"
      - "sysctl -w net.ipv4.ip_local_port_range='2000 65535'"
      - "sysctl -w net.ipv4.tcp_rfc1337=1"
      - "sysctl -w net.ipv4.tcp_syncookies=1"
      - "sysctl -w net.ipv4.tcp_fin_timeout=15"
      - "sysctl -w net.ipv4.tcp_keepalive_time=300"
      - "sysctl -w net.ipv4.tcp_keepalive_probes=5"
      - "sysctl -w net.ipv4.tcp_keepalive_intvl=15"
  - name: tuning network performance
    command: "{{ item }}"
    with_items:
      - "sysctl -w net.core.rmem_default=31457280"
      - "sysctl -w net.core.rmem_max=33554432"
      - "sysctl -w net.core.wmem_default=31457280"
      - "sysctl -w net.core.wmem_max=33554432"
      - "sysctl -w net.core.somaxconn=8096"
      - "sysctl -w net.core.netdev_max_backlog=65536"
      - "sysctl -w net.core.optmem_max=25165824"
      - "sysctl -w net.ipv4.tcp_max_syn_backlog=8192"
      - "sysctl -w net.ipv4.tcp_mem='786432 1048576 26777216'"
      - "sysctl -w net.ipv4.udp_mem='65536 131072 262144'"
      - "sysctl -w net.ipv4.tcp_rmem='8192 87380 33554432'"
      - "sysctl -w net.ipv4.udp_rmem_min=16384"
      - "sysctl -w net.ipv4.tcp_wmem='8192 65536 33554432'"
      - "sysctl -w net.ipv4.udp_wmem_min=16384"
      - "sysctl -w net.ipv4.tcp_max_tw_buckets=1440000"
      - "sysctl -w net.ipv4.tcp_tw_reuse=1"
      - "sysctl -w net.ipv4.tcp_fastopen=3"
      - "sysctl -w net.ipv4.tcp_window_scaling=1"