---
- name: gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_bios_version }}-{{ ansible_distribution }}.yml"
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ cloud_platform }}-{{ ansible_distribution }}.yml"
  tags:
    - vars

- name: download node_exporter package
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz
    dest: "{{ USER.home }}"

- name: tar node_exporter package
  unarchive:
    copy: no
    src: "{{ USER.home }}/node_exporter-0.18.1.linux-amd64.tar.gz"
    dest: "{{ USER.home }}"

- name: install node_exporter
  become: true
  shell: "mv -f {{ USER.home }}/node_exporter-0.18.1.linux-amd64/node_exporter /usr/local/bin"

- name: add node_exporter user
  become: true
  user:
    name: node_exporter
    comment: user for node exporter
    shell: /bin/false
    system: yes

- name: copy node_exporter service files
  become: true
  copy:
    src: node_exporter.service
    dest: /lib/systemd/system
  tags: cpconfig

- name: enable node_exporter service
  become: true
  systemd: 
    name: node_exporter
    daemon_reload: yes
    enabled: yes
    state: started

- name: clear trash
  ignore_errors: yes
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ USER.home }}/node_exporter-0.18.1.linux-amd64.tar.gz"
    - "{{ USER.home }}/node_exporter-0.18.1.linux-amd64"